interface Env {
  DB: D1Database;
  MEDIA_BUCKET: R2Bucket;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_OAUTH_REDIRECT_URI?: string;
  CODEX_API_TOKEN: string;
  SPRITES_API_TOKEN: string;
  BHART_ARTICLE_AGENT_ALLOWED_EMAILS?: string;
  BHART_ARTICLE_AGENT_SPRITE_NAME?: string;
  BHART_ARTICLE_AGENT_SPRITE_WORKDIR?: string;
  BHART_ARTICLE_AGENT_SPRITES_API_BASE?: string;
  SHOW_EMAIL_SUBSCRIBE?: string;
  RATE_LIMITER: DurableObjectNamespace;
  SEND_EMAIL: SendEmail;
}
